import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Heart from "react-animated-heart";
import { useState } from "react";
import Swal from "sweetalert2";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isClick, setClick] = useState(false);
  const [index, setIndex] = useState(0)
  const quotes = [
    "If anyone can do this, you can, I believe in you",
    "You are one of the strongest people I have ever met. This won’t beat you.",
    "Don't worry. You’ve got this. I support you and I'll continue fighting to win you.",
    "Look at how far you have come already. You’re stronger than any adversity. You’ve got this.",
    "I know it's hard right now, but it's worth doing. Believe in yourself.",
    "You’re prepared and ready. Nothing can stand in your way.",
    "I love you",
  ];

  const handleClick = () => {
    setTimeout(() => {
      Swal.fire({
        title: quotes[index],
        showClass: {
          popup: `
          animate__animated
          animate__fadeInUp
          animate__faster
        `,
        },
        hideClass: {
          popup: `
          animate__animated
          animate__fadeOutDown
          animate__faster
        `,
        },
      });
   
      setClick(false)
    }, 1000);
    if(index + 1 === 7)
      setIndex(0)
    else
    setIndex(index + 1); 
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.content}>
          <div className={styles.images}>
            <Image src="/sad.png" width={150} height={150} alt="sad" />
            <Image src="/1.webp" width={100} height={50} alt="1" />
          </div>
          <div className={styles.heartContent}>
            <h1>حاسس بانعدام الطاقة والشغف اضغط القلب</h1>
            <Heart
              isClick={isClick}
              onClick={() => {
                setClick(!isClick);
                handleClick();
              }}
            />
          </div>
        </div>
      </main>
    </>
  );
}
